[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
spotless = "7.0.3"
ksp = "2.2.21-2.0.4"
hilt = "2.57.1"
room = "2.8.0"
litert = "2.0.2"
djl = "0.33.0"
pdfboxAndroid = "2.0.27.0"
lifecycleViewModelCompose = "2.6.1"
objectbox = "5.0.1"
firebase = "4.4.4"
firebaseBom = "34.4.0"
coil = "3.3.0"
work = "2.11.0"
androidxHilt = "1.3.0"
datastore = "1.1.7"
material3 = "1.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
pdfbox-android = { group = "com.tom-roush", name = "pdfbox-android", version.ref = "pdfboxAndroid" }

# liteRT 라이브러리
litert = { group = "com.google.ai.edge.litert", name = "litert", version.ref = "litert" }

# djl 라이브러리
djl-android-core = { group = "ai.djl.android", name = "core", version.ref = "djl" }
djl-pytorch-engine = { group = "ai.djl.pytorch", name = "pytorch-engine", version.ref = "djl" }
djl-android-pytorch = { group = "ai.djl.android", name = "pytorch-native", version.ref = "djl" }
djl-android-tokeninzer = { group = "ai.djl.android", name = "tokenizer-native", version.ref = "djl" }
djl-huggingface-tokenizers = { group = "ai.djl.huggingface", name = "tokenizers", version.ref = "djl" }

# objectbox gradle plugin 라이브러리
objectbox-gradlePlugin = { module = "io.objectbox:objectbox-gradle-plugin", version.ref = "objectbox" }

# firebase ai login 관련 라이브러리
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-ai = { group = "com.google.firebase", name = "firebase-ai" }

# coil 라이브러리
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }

# WorkManager 라이브러리
work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }

# DatsStore 라이브러리
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
objectbox = { id = "io.objectbox" }
firebase = { id = "com.google.gms.google-services", version.ref = "firebase" }
